### ISSUE TITLE
Argument --recipe should be required and have no default

### ISSUE THREAD

**Issue by hholst80** [NVIDIA/hpc-container-maker#113]
The argument --recipe should just be a required argument with no default.

The current behavior is confusing for new users. Running hpccm with no arguments should show the help?

```
/ # hpccm
ERROR: [Errno 2] No such file or directory: 'recipes/hpcbase-gnu-openmpi.py'
/ # find / -name hpcbase-gnu-openmpi.py
/ #
```

**Comment by samcmill** [comment]
The example recipes are not included in the PyPi package.  You will need to download them separately.

But clearly the default recipe needs to change.  I think `--recipe` should just be a required argument with no default.

**Comment by hholst80** [comment]
I'll rephrase the bug and we can recycle it as such :) I hope you don't mind me borrowing your wording.
