### ISSUE TITLE
install_step for CMakeBuild

### ISSUE THREAD

**Issue by SimeonEhrig** [NVIDIA/hpc-container-maker#162]
Hello,
for my projects I need some open-source libraries, which I build from scratch. So I need to run `make install` for these libraries. Unfortunately, I can't find a Python function that generates the `make install` command. Did I miss something? If not, can we add a `install_step()`function to `CMakeBuild`? It would improve the readability and maintainability of my receipts. At the moment I'm using `shell()` functions.
Thank you for your help,
Simeon

**Comment by bilke** [comment]
Hi @SimeonEhrig just specify the `install`-target in the `build_step()`:

```python
build_step(target='install')
```

**Comment by SimeonEhrig** [comment]
Thank you for your answer. The solution works well.
