### ISSUE TITLE
problem copy from stage0 to stage1 with singularity 3.2 and singularity 3.4

### ISSUE THREAD

**Issue by alchemroz** [NVIDIA/hpc-container-maker#193]
Hello,
         I am trying to test the multistage capability of hpccm recipe made for singularity. I started with a simple example made for singularity 3.4. I want to build an image with pgi compiler starting from a  docker devel image in stage0, make the stage1 and move file from stage0 to stage1 according to the default recipe   

[hpcbase-pgi-1910-openmpi.py.txt](https://github.com/NVIDIA/hpc-container-maker/files/3864370/hpcbase-pgi-1910-openmpi.py.txt)
[recipe_hpcbase-pgi-1910-openmpi_runtime.ref.txt](https://github.com/NVIDIA/hpc-container-maker/files/3864371/recipe_hpcbase-pgi-1910-openmpi_runtime.ref.txt)

Using the following commands (in a server with Centos 7)

hpccm --recipe hpcbase-pgi-1910-openmpi.py --format singularity --singularity-version=3.4 > recipe_hpcbase-pgi-1910-openmpi_runtime.ref

sudo -E SINGULARITY_TMPDIR=/home/simone/Documents/sing_tmpdir SINGULARITY_CACHEDIR=/home/simone/Documents/sing_cachedir singularity -d img_hpcbase-pgi-1910-openmpi_runtime.sif recipe_hpcbase-pgi-1910-openmpi_runtime.ref

I got this error when I pass from stage0 to stage1, I used the -d option when I run the command

: [/home/simone/Documents/sing_tmpdir/sbuild-855637488 /home/simone/Documents/sing_tmpdir/sbuild-042428559]
FATAL   [U=0,P=13655]      run()                         While performing build: unable to copy files a stage to container fs: stage 0 was not found

I put my hpccm recipes, the corresponding singularity recipe in attachment

Could you please help me to understand what is going wrong ?

Thank you

**Comment by alchemroz** [comment]
Ok I got the issue, the 

Stage0 += baseimage(image=devel_image, _as='devel')

the "_as" no longer works, the name of Stage0 was not passed correctly to Stage1 indeed he was looking for a Stage0 called '0' when instead the current name of Stage 0 was devel because of the line

Stage: devel

inside the Singularity recipe. If in the stage1 I change the '%file from 0' to '%file from devel' it works for me. If it is a bug please correct it, it was quite harmful for a newbie like me.

Thanks.

**Comment by samcmill** [comment]
@alchemroz - thanks for the report.  I agree the documentation should be clearer about this.

I recommend you use the form `Stage1 += Stage0.runtime(_from='devel')` rather than the runtime method individually for each building block in your devel stage.  The result will be the same, but this form is more compact.  Looking closer, there may also be a way to read the name of the first stage automatically when using this form but not for the individual runtime calls, but I'll need to investigate further.

**Comment by alchemroz** [comment]
Thanks for the clarification @samcmill.

Cheers

**Comment by samcmill** [comment]
@alchemroz can you please take a look at #197 and let me know if you have any feedback?

**Comment by alchemroz** [comment]
Hello @samcmill , I agree with #197, in general I noticed some small changes between docker containers and singularity containers that produce nasty outcomes. The changes in #197 should solve this issue. 

Bests

**Comment by samcmill** [comment]
Closed via #197
