### ISSUE TITLE
NetCDF tarballs moved

### ISSUE THREAD

**Issue by jirikraus** [NVIDIA/hpc-container-maker#195]
The NetCDF tarballs are no longer available on  are no longer available on https://www.unidata.ucar.edu/downloads/netcdf/ftp they moved to GitHub:
- C: https://github.com/Unidata/netcdf-c/archive
- CXX: https://github.com/Unidata/netcdf-cxx4/archive
- Fortran: https://github.com/Unidata/netcdf-fortran/archive 

and changed their name to no longer include `netcdf-c-`, `netcdf-cxx4-` or `netcdf-fortran-` instead all tarballs just use `vX.Y.Z`, e.g. for `netcdf-c-4.6.3` the tarball URL is now `https://github.com/Unidata/netcdf-c/archive/v4.6.3.tar.gz`

**Comment by samcmill** [comment]
Fixed by #202
