### ISSUE TITLE
integration with EasyBuild?

### ISSUE THREAD

**Issue by boegel** [NVIDIA/hpc-container-maker#20]
I was referred to this (seemingly quite new) project by @gppezzi, which is quite interesting to us EasyBuilders since we have recently added support in EasyBuild (http://easybuilders.github.io/easybuild/) to generate Singularity definition files, and (optionally) also call out to Singularity to build the container image as well, see http://easybuild.readthedocs.io/en/latest/Containers.html .

It seems like it would be interesting and mutually beneficial to look into integration between HPCCM & EasyBuild, and I think this can be done in two main ways:

* HPCCM can be enhanced to provide an `easybuild` function, which can be used in recipe files to generate EasyBuild commands to install software, sort of similar to the `openmpi` function that is already supported

* EasyBuild can be enhanced to leverage HPCCM rather than implementing it's own functionality to create Docker/Singularity definition files

It's unclear to me whether HPCCM is currently ready to be used as a library rather than a command line tool, but if it's not we can probably contribute to making that work.

Maybe we should set up a conf call to discuss this further?

**Comment by samcmill** [comment]
Thanks for reaching out @boegel.  I'll contact you by email to setup a call.

**Comment by boegel** [comment]
Excellent! :+1:

**Comment by samcmill** [comment]
Closing.  EasyBuild recipe added by #23 and Python 2.7 compatibility for EasyBuild integration of HPCCM resolved by #25.

Please open a new issue if there are any unresolved EasyBuild integration issues.
