### ISSUE TITLE
Add ability to include llvm tools (clang-tidy/format)

### ISSUE THREAD

**Issue by acmnpv** [NVIDIA/hpc-container-maker#238]
Currently, adding the llvm building block only adds the base compiler to the image.
It would be great if it was also possible to add the corresponding tools as well, to allow the generated image to be used for source code linting.

**Comment by samcmill** [comment]
Yes, I can add `clang-format` and `clang-tidy` as an optional install.

It looks like the CentOS distro packages already include `clang-format` with the compiler.

**Comment by acmnpv** [comment]
Great!
I have worked around this for now by adding the install manually, but having this as an option in the script will be a cleaner solution.
