### ISSUE TITLE
Is there any possible to disable output of hpcx environment ?

### ISSUE THREAD

**Issue by likueimo** [NVIDIA/hpc-container-maker#245]
Many thanks for developing this amazing tool.  
I just want to use `hcoll library` which inside `hpcx` to compile with my openmpi.    
Then I try to use hpcx block, however this block will output all of hpcx environment.(include openmpi inside hpcx)  
Therefore, is there any possible to disable output of hpcx environment ?  
Thank you !

**Comment by samcmill** [comment]
Does `hpcx(environment=False, hpcxinit=False)` provide your desired behavior?

**Comment by likueimo** [comment]
@samcmill Yes, I think it should be awesome for adding `environment=False` !

**Comment by samcmill** [comment]
To be clear, `environment=False` is already supported.  However, it's not documented, which should be fixed.

**Comment by likueimo** [comment]
Sorry, I misunderstanding your first comment.  
Yes, it work now! Thanks again !
