### ISSUE TITLE
Jupyter recipe doesn't support conda environment names other than `base`

### ISSUE THREAD

**Issue by keipertk** [NVIDIA/hpc-container-maker#269]
When you generate an environment.yml file, the first line gives the name of your conda environment. If your environment name isn't the default `base`, then the Docker image produced by hpccm doesn't `conda activate` into the new environment before launching the Jupyter notebook. As a result, you don't have access to any of the conda packages you installed.

**Comment by samcmill** [comment]
@keipertk can you please try #270 and let me know if that fixes this issue for you?

**Comment by keipertk** [comment]
Yes that fixed the issue. Thanks!
