### ISSUE TITLE
Add the ability to download nv_hpc_sdk

### ISSUE THREAD

**Issue by hyviquel** [NVIDIA/hpc-container-maker#289]
Hi all! 

It does not seem the nv_hpc_sdk building block currently supports downloading the package and I am having trouble to create a recipe which does it automatically for my CI workflow.

I tried to implement my self this way:

```
d = downloader(url='https://xxxxxxxxxxxxxxxx/nvhpc_2020_207_Linux_x86_64_cuda_multi.tar.gz')
Stage0 += d.download_step()
Stage0 += nv_hpc_sdk(eula=True, mpi=False, system_cuda=True,
                                      tarball='nvhpc_2020_207_Linux_x86_64_cuda_multi.tar.gz')
```

Unfortunately I get a docker error when building: error building image: 
> parsing dockerfile: Dockerfile parse error line 57: unknown instruction: MKDIR

Anyone has an idea for me?
Thanks in advance!

**Comment by samcmill** [comment]
Try modifying the second line to

```
Stage0 += shell(commands=[d.download_step()])
```

Alternatively, an updated building block will be available soon that will do for you.  😄

**Comment by hyviquel** [comment]
Thanks for the tip, now I understand my mistake. We'll certainly move to the updated building block when available. 

My research team is using quite heavily and very successfully HPCCM so thanks it, very useful!

**Comment by samcmill** [comment]
Please see #291 for the changes to support downloading the HPC SDK.

Please note that the building name has changed from `nv_hpc_sdk` to `nvhpc` and many of the parameters have changed.
