### ISSUE TITLE
Add new building block for nsight compute

### ISSUE THREAD

**Issue by hyviquel** [NVIDIA/hpc-container-maker#292]
It would be nice to have a way to install nsight compute only without the rest of the HPC SDK.

**Comment by jmarusarz-NVIDIA** [comment]
Nsight Compute is available as a standalone install if you have the cuda repositories enabled. For example, a series of instructions like this could work:

echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/cuda.list 
wget -qO - https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub | apt-key add  

apt-get update -y
apt-cache search nsight-compute
apt-get install -y nsight-compute-2020.1.0

You may need to modify the paths for your environment. It's also available via yum for RHEL-based systems, e.g.:

rpm --import https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/7fa2af80.pub 
yum-config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64 
yum list available | grep nsight 
 yum install -y nsight-compute-2020.1.0

**Comment by samcmill** [comment]
A HPCCM recipe for this that covers both Ubuntu and CentOS would be something like

```
Stage0 += packages(
    apt=['apt-transport-https', 'ca-certificates', 'gnupg', 'wget'])
Stage0 += packages(
    apt_keys=['https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub'],
    apt_repositories=['deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /'],
    ospackages=['nsight-compute-2020.1.0'],
    yum_keys=['https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/7fa2af80.pub'],
    yum_repositories=['https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64'])
```

**Comment by hyviquel** [comment]
thanks
