### ISSUE TITLE
wrong gfortran runtime library on ubuntu:18.04

### ISSUE THREAD

**Issue by avaldebe** [NVIDIA/hpc-container-maker#299]
The `gfortran` runtime library for Ubuntu based images is set to `libgfortran3`

https://github.com/NVIDIA/hpc-container-maker/blob/adbe43fef9fca99905b0e9363ee538c7b95ec1e0/hpccm/building_blocks/gnu.py#L409-L411

This is correct on `ubuntu:16.04`. However on `ubuntu:18.04` this should be `libgfortran4`, and `libgfortran5` on `ubuntu:20.04`.

-  [ubuntu:16.04 gfortran][xenial] --> gfortran-5 --> libgfortran3-dbg --> libgfortran3
-  [ubuntu:18.04 gfortran][bionic] --> gfortran-7 --> libgfortran7-dbg --> libgfortran4
-  [ubuntu:20.04 gfortran][focal] --> gfortran-9 --> libgfortran9-dbg --> libgfortran5

[xenial]: https://packages.ubuntu.com/xenial/gfortran
[bionic]: https://packages.ubuntu.com/bionic/gfortran
[focal]: https://packages.ubuntu.com/focal/gfortran

Would you be interested on a PR?

**Comment by samcmill** [comment]
Thanks for the report!  I'll investigate further and post a fix.

**Comment by samcmill** [comment]
@avaldebe please take a look at #304.  

Support for Ubuntu 20.04 is a larger change.  I'll make sure this is updated when Ubuntu 20.04 support is added.

**Comment by avaldebe** [comment]
@samcmill #304 is much more involved than the simple patch I implemented locally.
Besides a new test, I added a few lines on __instructions. Dealing with this on __distro makes more sense, even if the changes are larger.

Thanks for solving this issue.
