### ISSUE TITLE
conda: allow changing python subversion

### ISSUE THREAD

**Issue by adegomme** [NVIDIA/hpc-container-maker#310]
Hi,
our workflow needs for the moment a python 3.7 version of conda (nothing I can change on our side). Until last version, I was able to retrieve it by giving 'py37_4.8.3' as version argument, but since this version, the version argument is strictly checked in its format, and py38 (or py27) is forced.
Could the __python_version be modified by the user as well ? That would be useful for us.

**Comment by samcmill** [comment]
Good point.  I will make this configurable.
