### ISSUE TITLE
fail to build NetCDF 4.7.3 with 20.9.0

### ISSUE THREAD

**Issue by avaldebe** [NVIDIA/hpc-container-maker#316]
After updating from 20.8.0 to 20.9.0 my scripts fail to build NetCDF 4.7.3 with the following error

```
configure: error: netcdf-c version 4.7.4 or greater is required
```

Before the update, NetCDF 4.7.3 meant  netcdf-c/4.7.3 with netcdf-cxx4/4.3.1 and netcdf-fortran/4.5.2,
after the update it tries to compile with netcdf-fortran/4.5.3. This seems to be the cause of the error.

The following `recipe.py` will build without issues on 20.8.0 and trigger the error on 20.9.0

```python
Stage0 += baseimage(image="ubuntu:18.04", _as='build')

# gCC & gFortran
compiler = gnu()
Stage0 += compiler

# OpenMPI
Stage0 += openmpi(version="4.0.2", infiniband=False, cuda=False, toolchain=compiler.toolchain)

# HDF5
Stage0 += hdf5(version="1.10.5", toolchain=compiler.toolchain)

# NetCDF
Stage0 += netcdf(version="4.7.3", toolchain=compiler.toolchain)
```

**Comment by samcmill** [comment]
The netcdf-c version is pinned, but the netcdf-cxx and netcdf-fortran versions are not so the (new) default versions are used.  Please try setting `version_fortran=4.5.2` and `version_cxx=4.3.1` to pin all 3 versions.

**Comment by avaldebe** [comment]
Yes, my mistake was to assume that I only needed to pin the `netcdf-c` version.
I see now that I also need to the `netcdf-cxx` and `netcdf-fortran` versions.
