### ISSUE TITLE
Netcdf with pnetCDF support

### ISSUE THREAD

**Issue by VI-gha** [NVIDIA/hpc-container-maker#342]
What is the correct syntax to install netcdf with pnetcdf support using hpc-container-maker?

Assuming that pnetcdf is installed in /usr/local/pnetcdf, it does not seem sufficient to add 

enable_pnetcdf='/usr/local/pnetcdf'

Whatever I tried nc-config --all always shows --has-pnetcdf   -> no

**Comment by samcmill** [comment]
This basic recipe works for me:

```
Stage0 += baseimage(image='ubuntu:18.04')

Stage0 += gnu()
Stage0 += openmpi(cuda=False, infiniband=False)
Stage0 += hdf5()
Stage0 += pnetcdf()
Stage0 += environment(variables={'CPATH': '/usr/local/openmpi/include:/usr/local/pnetcdf/include:$CPATH',
                                 'LIBRARY_PATH': '/usr/local/pnetcdf/lib:$LIBRARY_PATH'})
Stage0 += netcdf(enable_pnetcdf=True)
```

It looks like the `pnetcdf` building block should set `CPATH` and `LIBRARY_PATH`.

I'm not sure if the `openmpi` building block should set `CPATH` or not - normally one would use the MPI compiler wrappers for that.

**Comment by VI-gha** [comment]
OK, thanks a lot, that worked with CPATH and LIBRARY_PATH
    On Tuesday, 23 February 2021, 17:57:51 CET, Scott McMillan <notifications@github.com> wrote:  
 
 


This basic recipe works for me:
Stage0 += baseimage(image='ubuntu:18.04')

Stage0 += gnu()
Stage0 += openmpi(cuda=False, infiniband=False)
Stage0 += hdf5()
Stage0 += pnetcdf()
Stage0 += environment(variables={'CPATH': '/usr/local/openmpi/include:/usr/local/pnetcdf/include:$CPATH',
                                 'LIBRARY_PATH': '/usr/local/pnetcdf/lib:$LIBRARY_PATH'})
Stage0 += netcdf(enable_pnetcdf=True)

It looks like the pnetcdf building block should set CPATH and LIBRARY_PATH.

I'm not sure if the openmpi building block should set CPATH or not - normally one would use the MPI compiler wrappers for that.
