### ISSUE TITLE
How to specify the architecture in a conda building block?

### ISSUE THREAD

**Issue by VI-gha** [NVIDIA/hpc-container-maker#351]
By default when installing Anaconda the architecture is _Linux-x86_64_ (with Miniconda3-py38_4.8.3-Linux-x86_64.sh).
How to change to _Linux-ppc64le_ (which would require for example Miniconda3-py38_4.9.2-Linux-ppc64le.sh)?

**Comment by samcmill** [comment]
You should just need to start from a ppc64le base image, e.g.,

```
Stage0 += baseimage(image='ppc64le/centos:7')
Stage0 += conda(eula=True, packages=['numpy', 'scipy'])
```

If your base image does not have an identifiable `ppc64le` name, you can specify it, e.g.,

```
Stage0 += baseimage(image='myimage', _arch='ppc64le')
Stage0 += conda(...)
```

**Comment by VI-gha** [comment]
Great, thanks !
