### ISSUE TITLE
Mellanox HPC-X installation error

### ISSUE THREAD

**Issue by XiaoleiShi-NV** [NVIDIA/hpc-container-maker#384]
The link points to HPC-X package is invalid anymore: http://www.mellanox.com/downloads/hpc/hpc-x/v2.8/hpcx-v2.8.1-gcc-MLNX_OFED_LINUX-4.7-1.0.0.1-ubuntu18.04-x86_64.tbz

**Comment by samcmill** [comment]
Do you have #382 / 21.6.0?

**Comment by XiaoleiShi-NV** [comment]
No, I'm using 20.7.0 installed through pip.

**Comment by samcmill** [comment]
Closing as resolved in 21.6.0.  Please reopen if the issue persists.
