### ISSUE TITLE
Upload universal wheel to PyPi

### ISSUE THREAD

**Issue by bilke** [NVIDIA/hpc-container-maker#385]
For releases can you please create and upload a universal wheel in addition to the source distribution? You can create them with:

```bash
python setup.py bdist_wheel --universal
```

I am trying to run hpccm in [JupyterLite](https://jupyterlite.readthedocs.io/) and installation in this environment requires a wheel:

```python
import micropip
await micropip.install("hpccm")
...
ValueError: Couldn't find a pure Python 3 wheel for 'hpccm'
```

**Comment by samcmill** [comment]
@bilke I uploaded a wheel for 21.6 (https://pypi.org/project/hpccm/21.6.0/#files).  Please let me know if that works for you and I'll make it a standard part of releases going forward.

**Comment by bilke** [comment]
@samcmill Thanks a lot! Yes it works:

```python
import micropip
await micropip.install('six')
await micropip.install('archspec')
await micropip.install('hpccm')
import hpccm

Stage0 = hpccm.Stage()
Stage0 += hpccm.building_blocks.gnu()
Stage0 += hpccm.building_blocks.nvhpc(eula=True)
print(Stage0)
...
```
