### ISSUE TITLE
ucx() problem with versions with the suffix -rc

### ISSUE THREAD

**Issue by lmagdanello** [NVIDIA/hpc-container-maker#467]
**What happens** is that when using versions with the _-rc_ suffix with the UCX building block, we encounter the following issue: 

The module attempts to download the path: `https://github.com/openucx/ucx/releases/download/v1.15.0-rc4/ucx-1.15.0-rc4.tar.gz`. However, UCX provides the path for _-rc_ versions in the following way: _https://github.com/openucx/ucx/releases/download/v1.15.0-rc4/ucx-1.15.0.tar.gz._

### Recipe:
`Stage0 += ucx(version='1.15.0-rc4')`

### Log:
```shell
The command '/bin/sh -c mkdir -p /var/tmp && 
wget -q -nc --no-check-certificate -P /var/tmp **https://github.com/openucx/ucx/releases/download/v1.15.0-rc4/ucx-1.15.0-rc4.tar.gz** &&  
mkdir -p /var/tmp && tar -x -f /var/tmp/ucx-1.15.0-rc4.tar.gz -C /var/tmp -z &&     
cd /var/tmp/ucx-1.15.0-rc4 &&  
 ./configure --prefix=/usr/local/ucx 
--disable-assertions 
--disable-debug 
--disable-doxygen-doc 
--disable-logging 
--disable-params-check 
--enable-optimizations 
--without-cuda &&     
make -j$(nproc) &&     
make -j$(nproc) install &&     
rm -rf /var/tmp/ucx-1.15.0-rc4 /var/tmp/ucx-1.15.0-rc4.tar.gz' returned a non-zero code: 8
```

**Comment by lmagdanello** [comment]
My idea is that with this simple regex, we can give users the freedom to use pre-release versions.

**Comment by samcmill** [comment]
Does this work?

```
Stage0 += ucx(url='https://github.com/openucx/ucx/releases/download/v1.15.0-rc4/ucx-1.15.0.tar.gz')
```

**Comment by lmagdanello** [comment]
I was thinking about my suggestion and thought of another solution: perhaps the UCX building block can receive _pre_release_ as a parameter and if it is **True** it will deal with versions with the _-rc_ suffix. What do you think?

**Comment by samcmill** [comment]
I am concerned about maintaining the pre-release logic.  

Since there is a straightforward workaround using the `url` parameter, I'm inclined not to try to fix this.

**Comment by lmagdanello** [comment]
Of course, I understand. I'll close the issue in this case then.
