### ISSUE TITLE
Error while using "node:latest" base image on HPCCM

### ISSUE THREAD

**Issue by borin98** [NVIDIA/hpc-container-maker#469]
Hello guys !. I'm using hpccm to build a Dockerfile with node:latest and I got the following Warning

```{.sh}
WARNING: Unable to determine the Linux distribution, defaulting to Ubuntu
```

Looking into the function `set_linux_distro` It's seems that function doesn't include Node into the package. It's possible to open a pull request to implement a **Node** in this function ?

**Comment by samcmill** [comment]
HPCCM uses the image name to determine the Linux distribution.  The `baseimage` building block has the `_distro` option to override the auto-detection capability, or to use when the autodetection can't figure it out.

The node:latest image is based on Debian 12.  The closest distro that HPCCM supports is probably Ubuntu 22.04.

```
Stage0 += baseimage(image='node:latest', _distro='ubuntu22')
```

**Comment by borin98** [comment]
Thanks for the help @samcmill! Your comment help's me to create a dockerfile with node. I'll close this issue
