### ISSUE TITLE
LLVM trunk version out-of-date

### ISSUE THREAD

**Issue by al42and** [NVIDIA/hpc-container-maker#471]
Since Jul 26th 2023, LLVM trunk is version 18.

`self.__trunk_version` in `hpccm/building_blocks/llvm.py` should be bumped to allow installing Clang 17 or 18.

**Comment by samcmill** [comment]
I have updated the building block, but the undocumented `_trunk_version` option can be used to override the default behavior, e.g., `llvm(upstream=True, _trunk_version='18')`.
