### ISSUE TITLE
Replace use of deprecated apt-key

### ISSUE THREAD

**Issue by mabraham** [NVIDIA/hpc-container-maker#495]
The use of apt-key has been deprecated for two years, so it would be good to update. Debian's official advice is [here](https://wiki.debian.org/DebianRepository/UseThirdParty).

See for example https://askubuntu.com/questions/1328806/how-to-solve-apt-key-deprecated for an approach that I think should work well for Ubuntu.

The apt commands written to the hppcm Docker build file need to be changed accordingly.

**Comment by samcmill** [comment]
Agreed.  The `_apt_key` parameter default should be changed from True to False and all the test cases will need to be updated.
