### ISSUE TITLE
Using older version of PGI compiler 17.10 does not work

### ISSUE THREAD

**Issue by dshawul** [NVIDIA/hpc-container-maker#57]
If I try to use older PGI compiler version 17.10, it still copies the latest PGI community edition compiler
There is the following comment in the code which makes me think that it is not supposed to work using but the latest version

        # The version is fragile since the latest version is
        # automatically downloaded, which may not match this default.
        self.__version = kwargs.get('version', '18.4')
        self.__wd = '/var/tmp' # working directory

**Comment by samcmill** [comment]
PGI only makes the most recent version of the PGI Community Edition available for download.  Currently that is version 18.4.  

The `version` parameter does not actually control the version that is downloaded.  However, the version is needed to properly configure the component, e.g., `$PATH`.  Hence this comment.

The documentation in RECIPES.md is
```
- `version`: The version of the PGI compiler to use.  Note this value
  is currently only used when setting the environment and does not
  control the version of the compiler downloaded.  The default value
  is `18.4`.
```

If you have a tarball of a previous version of the PGI compiler, you can use it with the PGI building block via the `tarball` parameter:

```
Stage0 += pgi(tarball='pgilinux-2017-1710-x86_64.tar.gz', ...)
```

But if you do not have a local copy of a previous version, there is no combination of options that will download an older version.

If you have a PGI Professional Edition license, you can download older versions manually from the website and use the `tarball` option.
