### ISSUE TITLE
Add cmake support for build stage

### ISSUE THREAD

**Issue by mathiaswagner** [NVIDIA/hpc-container-maker#8]
The ubuntu default cmake might not always be the latest and greatest.
Cmake binaries are readily available at https://cmake.org/download/.
The `.sh` files unpack in the default system location.

E.g. in my singularity files I use
```
        # CMAKE
        wget https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.sh
        sh cmake-3.10.0-Linux-x86_64.sh  --skip-license
        rm cmake-3.10.0-Linux-x86_64.sh
```
to install cmake.

I might be able to figure out on my own how to do it but would need to find some time.

**Comment by samcmill** [comment]
Added by #13
